name: Terraform Deployment

on:
    push:
        branches: [main]

jobs:
    build-runner:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4
            
            -   name: Change Directory
                run: cd runner-setup
            
            -   name: Install Terraform
                uses: hashicorp/setup-terraform@v3
            
            -   name: Initializing terraform
                run: terraform init

            -   name: Apply Terraform
                run: terraform apply -auto-approve
    #deployment:
    #    runs-on: self-hosted
    #    steps:
    #        -   name: Checkout Repository
    #            uses: actions/checkout@v4
    #        
    #        -   name: Install Terraform
    #            uses: hashicorp/setup-terraform@v3
    #        
    #        -   name: Initializing terraform
    #            run: terraform init
    #        
    #        -   name: Select Test Workspace
    #            run: terraform workspace select test
    #        
    #        -   name: Apply Terraform
    #            run: terraform apply -var-file=config/test.tfvars -auto-approve