name: Terraform Deployment

on:
    push:
        branches: [main]

jobs:
    build-runner:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Install Terraform
            uses: hashicorp/setup-terraform@v3

          - name: Terraform Init
            working-directory: ./runner-setup
            run: terraform init

          - name: Terraform Apply
            working-directory: ./runner-setup
            run: terraform apply -auto-approve
    deployment:
        needs: build-runner
        runs-on: self-hosted
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4
            
            -   name: Install Terraform
                uses: hashicorp/setup-terraform@v3
            
            -   name: Initializing terraform
                run: terraform init
            
            -   name: Select Test Workspace
                run: terraform workspace select test
            
            -   name: Terraform Apply Command
                run: terraform apply -var-file=config/test.tfvars -auto-approve